name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Inflate google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo -e $GOOGLE_SERVICES_JSON

      - name: Inflate local gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: echo -e $GRADLE_PROPERTIES

#      - name: Inflate local.gradle
#        env:
#          LOCAL_GRADLE: ${{ secrets.LOCAL_GRADLE }}
#        run: echo $LOCAL_GRADLE > app/local.gradle

      - name: Inflate and decript keystore.p12
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
        run:
          echo -e $RELEASE_KEYSTORE > app/keystore.p12.asc
          gpg -d --passphrase $RELEASE_KEYSTORE_PASSPHRASE --batch app/keystore.p12.asc > app/keystore.p12

#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew assemble
