name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Inflate google-services.json from secrets
        run: echo ${{ secrets.GOOGLE_SERVICES_JSON }} > app/google-services.json

      - name: Inflate app level gradle.properties from secrets
        run: echo ${{ secrets.GRADLE_PROPERTIES }} > app/gradle.properties

      - name: Inflate and decript keystore.p12 from secrets
        run: |
          echo ${{ secrets.RELEASE_KEYSTORE }} > app/keystore.p12.asc
          gpg -d --passphrase ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }} --batch keystore.p12.asc > keystore.p12

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble
