name: Android CI
# see also https://docs.github.com/en/actions/reference/encrypted-secrets
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

#    runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Inflate google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > app/google-services.json

      - name: Inflate local gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }} # new lines in secret must be \n
        run: echo -e $GRADLE_PROPERTIES  > app/gradle.properties

      - name: Decrypt keystore.p12
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
        run: gpg -d --passphrase $KEYSTORE_PASSPHRASE --batch app/keystore.p12.gpg > app/keystore.p12

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Run unit tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 30
#          script: ./gradlew connectedCheck

      - name: Assemble release
        run: ./gradlew assemble

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs/apk/release/*.apk