name: Release

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release APK
        run: echo VER = ${GITHUB_REF#refs/*/}
