name: Release

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release APK
#        env:
#          RELEASE_VERSION: ${{GITHUB_REF#refs/*/}}
        run: echo VER = $GITHUB_REF
